version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: meteo_postgres
    environment:
      POSTGRES_DB: meteo_france
      POSTGRES_USER: meteo_user
      POSTGRES_PASSWORD: meteo_pass
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5434:5432"

  metabase:
    image: metabase/metabase
    container_name: meteo_metabase
    ports:
      - "3000:3000"
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: meteo_france
      MB_DB_PORT: 5432
      MB_DB_USER: meteo_user
      MB_DB_PASS: meteo_pass
      MB_DB_HOST: postgres
    depends_on:
      - postgres

volumes:
  pgdata:
